### ISSUE TITLE
I am keen to join your team and utilize my expertise to help achieve outstanding results on your projects.

### ISSUE THREAD

**Issue by 0x0factor** [Team-Wash/Wash-Android#1]
Hi, I'm Ethan Tan, a web full-stack and blockchain developer with extensive experience spanning over 8 years. I specialize in developing resilient, scalable web applications and state-of-the-art blockchain solutions. My expertise in frameworks like React.js, Vue.js, and Next.js, along with my proficiency in Solidity for smart contract development, ensures I deliver premium, secure, and efficient solutions tailored to your specific needs.

**Comment by tristanjung1006** [comment]
totally appreciation for your support, but this project is based on university club in south korea
so...which means this does not SUIT with you.
thank u for saying and if you are still interested in this repository, plz use discussion tab later!
